### ISSUE TITLE
Toolbar buttons inactive

### ISSUE THREAD

**Issue by macauley** [K3TZR/xSDR6000#3]
I am running v1.2.1 with a 6400 on version 3.1.12, don't know if this is a compatibility issue with this latest radio version (app does warn me about the unsupported API version), but when running with this combination, I am observing that all of the toolbar buttons are grayed out and inactive. I have attached a screenshot which shows it:

<img width="1983" alt="Screen Shot 2020-06-05 at 11 02 33 AM" src="https://user-images.githubusercontent.com/213539/83908731-73168500-a71c-11ea-84e2-e374e2d56d24.png">

**Comment by K3TZR** [comment]
Thanks Eric.

The warning is just because all of my testing so far is with 3.1.11. More than likely, 3.1.12 works fine, I just haven’t proven it yet.

The buttons are a know problem that I can’t seem to reproduce here. I’m sure it’s something stupid.The previous version didn’t have this problem (but had other issues). I’m working on it and hopefully will be able to do an update in the next day or two.

Thanks for trying the app and taking the time to report your observation.

73’s 
Doug - K3TZR

**Comment by ww1ss** [comment]
The buttons don't work in 3.1.12 . . . Only the disconnect button works

------ Original Message ------

**Comment by macauley** [comment]
Hi Doug, just FYI, I tried the latest 1.2.2 version, I notice now that the toolbar buttons activate, but then they deactivate once I click on the "Continue" for the API warning. Attached is a quick screen recording.
[Screen Recording 2020-06-07 at 2.39.49 PM.mov.zip](https://github.com/K3TZR/xSDR6000/files/4743059/Screen.Recording.2020-06-07.at.2.39.49.PM.mov.zip)

**Comment by K3TZR** [comment]
Thanks Eric,

Your message finally got me to look in the right place, the Version Warning. I was testing with 3.1.11 and therefore never got the version warning (and didn’t see the issue). The modal sheet was disabling the Toolbar buttons. Since the warning didn’t really serve much purpose, I removed it. There is still a warning written to the log for debugging purposes.

73’s 
Doug - K3TZR

**Comment by macauley** [comment]
Thanks Doug, 1.2.3 fixes it! Marking this issue closed.

73,
Eric - KI6SCT
