### ISSUE TITLE
Can't use Mac internal microphone with xSDR6000

### ISSUE THREAD

**Issue by ofadam** [K3TZR/xSDR6000#6]
Is there a way to use the Mac internal microphone with xSDR6000? I've tried every possible audio combo to no avail.

**Comment by K3TZR** [comment]
I have not tried using the internal microphone. In the v3 API, It would need to be setup as a RemoteTxAudioStream (which is implemented in the underlying xLib6000) but, at least for now, there isn’t any way to configure it in xSDR6000.

Way back in a previous V2 API version I had that working somewhat but I have not made the changes needed for V3 and haven’t tested it (even the V2 version).

Sorry. I’ve been busy learning SwiftUI and haven’t updated xSDR6000 recently. I hope to get back to it in a month or two.

73’s Doug

**Comment by ofadam** [comment]
I appreciate the quick reply! I only have V2 software loaded on my Flex 6400, so would that mean that there's a config setup that might work (as opposed to V3)?

**Comment by K3TZR** [comment]
Adam,

I’m not certain. It worked at one point but I have not tested with V2 for a while. There is a problem downgrading the radio from v3 to V2 that has prevented me from testing using v2.

Theoretically xLib6000 and xSDR6000 will work with any v2 or v3 radio.

Audio is a complicated topic. As I recall the default audio input in the Mac has to be set to a sample rate of 24,000 or 48,000. In xSDR6000, the mic source has to be set to PC (or is it MAC, I don’t remember). It works in the same fashion as it does in  SmartSDR -Windows.

It’s been a long time since I tested it and there have been a lot of v3 related changes since them. Some of those changes may have caused issues in v2 operation.

I wish I had a better answer but I would need to downgrade my radio and try it myself to provide better guidance.

73’s Doug

**Comment by ofadam** [comment]
Hi Doug! Any luck in using the Mac's internal microphone be used for xSDR6000? I'd asked about v2, but does it work on v3?

**Comment by K3TZR** [comment]
Adam,The simple answer is no. I haven’t been making changes to xSDR6000 for some time now. I did make one recently to fix a crash that occurs with some of the newer Flex firmware versions.I’m still working on a completely new app to replace xSDR6000 but I’m a long way from done. The new app will definitely have Mac audio since I’m now living in a condo and will need a remote radio installation.73’s DougOn Nov 12, 2022, at 00:31, Adam ***@***.***> wrote:﻿
Hi Doug! Any luck in using the Mac's internal microphone be used for xSDR6000? I'd asked about v2, but does it work on v3?

**Comment by ofadam** [comment]
Understood! Best of luck with the new app – I'm not much of a coder, but happy to help test if helpful.
